# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_quote', models.TextField()),
                ('source_url', models.CharField(max_length=200)),
                ('source_title', models.CharField(max_length=200)),
                ('source_name', models.CharField(max_length=200)),
            ],
        ),
    ]
