# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 04:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
