# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 02:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0004_auto_20160418_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 21, 44, 52, 618254)),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 21, 44, 52, 616538)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 18, 21, 44, 52, 617421)),
        ),
    ]
