# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 23:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0009_user_domain_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='domain_list',
        ),
        migrations.AddField(
            model_name='user',
            name='domains',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
