# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0010_auto_20160420_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user_id',
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lookup.User'),
        ),
    ]
