# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0011_auto_20160424_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='highlighting_state',
            field=models.IntegerField(default=2),
        ),
    ]
