# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 23:37
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0012_user_highlighting_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trusted_sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='untrusted_sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
