# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 21:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0013_auto_20160426_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='other_article_titles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='source',
            name='other_article_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(),
        ),
    ]
