# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0016_auto_20160501_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='other_trusted',
        ),
        migrations.RemoveField(
            model_name='source',
            name='other_untrusted',
        ),
        migrations.RemoveField(
            model_name='source',
            name='trusted',
        ),
        migrations.RemoveField(
            model_name='source',
            name='untrusted',
        ),
    ]
