# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0017_auto_20160510_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='highlight_url',
        ),
    ]
